config/routes.rb
QnA::Application.routes.draw do
 

  root :to => 'landing#start'  
  devise_for :users

match "/questions/:id" => "questions#question", :as => "questions_url"  

match "/questions/:id/answers/:id" => "questions#question" 

resources :users do
    resources :answers
end

resources :user_activities

ActionController::Routing::Routes.draw do |map|

  map.connect '/questions/', :controller=>'questions', :action=>'create'
  map.connect '/landing/(:id)', :controller=>'landing', :action=>'start'
  map.connect '/questions/:id', :controller=>'questions', :action=>'question'

end

 resources :answers
 resources :users, :only => [:create]
 resources :questions, :only => [:create]
 match 'landing' => 'landing#start', :as => :landing 
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

	def start
	  
	  		flash[:notice]="Hey, How are you??"
	  		puts 'print='
	  		puts ((11.to_s * 2).to_i/2)
			@recent_questions_array= recent_questions()
	  		@user = User.new
	  		@user.id=params[:id]
 	  	 	@question = Question.new
            respond_to do |format|
     		  format.html # new.html.erb
      		  format.xml  { render :xml => @user }
		    end
	  
	end

	def recent_questions #methos to find recent question 
		@user_id=24

        array=Question.limit('4').order('updated_at desc')
        
	end


end

app/helpers/landing_helper.rb
module LandingHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end


end

app/views/landing/start.erb
<div id="outer-container">
 
 <div id="container">
		
     <div id="login-form">	
<%  puts 'Hello' 
    puts @user[:id] %>

<%= form_for(resource_name, resource, :url => session_path(resource_name)) do |f| %>
  
  <div class="field outer">
    <%= f.label :Email %>
    	<br clear="all" />
    <%= f.text_field :email %>
  </div><br clear="all" />
  
  <div class="field outer">
    <%= f.label :Password %><br />
    <%= f.password_field :password %>
  </div>
 
 <br clear="all" /><br clear="all" />
 
  <div class="actions">
    <%= f.submit :value => 'Log/Register'%>
  </div>
  <br clear="all" />
<% end %>



  </div><!-- login-form ends-->

		<br clear="all" />
		<br clear="all" />
		<br clear="all" />
		<br clear="all" />


<div id="question-container">

	<%= form_for(@question) do |f| %>
  		<% if @question.errors.any? %>
    		<div id="error_explanation">
      			<h2><%= pluralize(@question.errors.count, "error") %> prohibited this man from being saved:</h2>

    		  	<ul>
    			  <% @question.errors.full_messages.each do |msg| %>
        			<li><%= msg %></li>
      			  <% end %>
      		 	</ul>
        	</div>
   		<% end %>

  	<div class="field">
      	<%= f.text_area :description , :value=> 'Ask your Question !!' , :cols=>"90" , :rows=>"10" %>
 		<%= f.submit :value => 'Ask' , :disabled=> ( ! user_signed_in?  ? 'true' : nil ) %>
  	</div>
  
  	<div class="actions">
    	
   	</div>
 <% end %>  
</div>



  <div id="recent-questions">
	   <ul>
   
           <% @recent_questions_array.each do |question| %>
 		         
            <% link_to "/questions/#{question.id}" do %>
             <li>
                  <p class="question-desc">
                    <%= question.description%>
                    
				          </p>  
	          </li>
             <%end%>
          <%end%>   
	
	</ul>
</div>

  
  </div> <!--container ends-->

</div> <!-- outer-container ends-->